In [1]:
from project1 import *
import numpy as np

np.set_printoptions(precision=6,linewidth=200,suppress=True)

# n12 = 2

In [2]:
n12 = 2

cc2 = Configurations(n12, Z=2)#, eta=1.185185)
E_opt, eta_opt = cc2.optimize_eta()
E = cc2.get_energy()

States: [[1, 1, 0]]

Total number of states: 1

Minimized E = -2.847656   for eta = 1.185185

Results:  E = -2.847656 ,  eta = 1.18519 
Reference optimized values from the book:   E_ref = -2.847656  ,  eta_ref = 1.18519  ,  dE = 0.0000002


In [3]:
cc2.overlap

array([[1.]])

In [4]:
cc2.hamiltonian

array([[-1.]])

In [5]:
cc2.hamiltonian0

array([[-1.37037]])

In [6]:
cc2.hamiltonianW

array([[0.37037]])

In [7]:
cc2.eigenvalues

array([-2.847656])

# n12 = 3

In [8]:
n12 = 3

cc3 = Configurations(n12, Z=2)#, eta=1.185)
E_opt, eta_opt = cc3.optimize_eta()
E = cc3.get_energy()

States: [[1, 1, 0], [1, 2, 0]]

Total number of states: 2

Minimized E = -2.847656   for eta = 1.185181

Results:  E = -2.847656 ,  eta = 1.18518 
Reference optimized values from the book:   E_ref = -2.847656  ,  eta_ref = 1.18519  ,  dE = 0.0000002


In [9]:
cc3.overlap

array([[ 1.      , -0.707107],
       [-0.707107,  1.25    ]])

In [10]:
cc3.hamiltonian0

array([[-1.370362,  0.838049],
       [ 0.838049, -1.027771]])

In [11]:
cc3.hamiltonianW

array([[ 0.370369, -0.130945],
       [-0.130945,  0.277777]])

In [12]:
cc3.eigenvalues

array([-2.847656, -0.949205])

# n12 = 4

In [19]:
n12 = 4

cc4 = Configurations(n12, Z=2,eta=0.971)
#E_opt, eta_opt = cc4.optimize_eta()
E = cc4.get_energy()

States: [[1, 1, 0], [1, 2, 0], [1, 3, 0], [2, 2, 0], [2, 2, 1]]

Total number of states: 5
ETA: 0.971

Results:  E = -2.895444 ,  eta = 0.97100 
Reference optimized values from the book:   E_ref = -2.895444  ,  eta_ref = 0.97100  ,  dE = 0.0000005


In [20]:
cc4.overlap

array([[ 1.      , -0.707107,  0.      ,  0.5     ,  0.      ],
       [-0.707107,  1.25    , -0.612372, -1.414214,  0.      ],
       [ 0.      , -0.612372,  1.5     ,  0.866025,  0.      ],
       [ 0.5     , -1.414214,  0.866025,  4.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      ,  0.      ,  4.      ]])

In [21]:
cc4.hamiltonian0 

array([[-0.942   ,  0.686601,  0.      , -0.5     ,  0.      ],
       [ 0.686601, -0.7065  ,  0.594614,  0.686601,  0.      ],
       [ 0.      ,  0.594614, -0.442   , -0.866025,  0.      ],
       [-0.5     ,  0.686601, -0.866025,  0.116   ,  0.      ],
       [ 0.      ,  0.      ,  0.      ,  0.      ,  0.116   ]])

In [22]:
cc4.hamiltonian0 * 16

array([[-15.072   ,  10.985611,   0.      ,  -8.      ,   0.      ],
       [ 10.985611, -11.304   ,   9.513818,  10.985611,   0.      ],
       [  0.      ,   9.513818,  -7.072   , -13.856406,   0.      ],
       [ -8.      ,  10.985611, -13.856406,   1.856   ,   0.      ],
       [  0.      ,   0.      ,   0.      ,   0.      ,   1.856   ]])

In [23]:
cc4.hamiltonianW * 4.8550 / 0.303437

array([[ 4.855008, -1.716505, -0.840912,  1.456502, -1.962128],
       [-1.716505,  3.641256, -0.594615, -3.261359,  2.081151],
       [-0.840912, -0.594615,  3.27713 ,  1.471596,  0.121375],
       [ 1.456502, -3.261359,  1.471596,  9.34589 , -3.15342 ],
       [-1.962128,  2.081151,  0.121375, -3.15342 , 13.472647]])

In [24]:
cc4.eigenvalues

array([-2.895444, -1.432852,  1.018445,  2.431065,  4.524314])

# n12 = 5

In [25]:
n = 5

cc5 = Configurations(n, Z=2, eta=0.940)
#E_opt, eta_opt = cc5.optimize_eta()
E = cc5.get_energy()

States: [[1, 1, 0], [1, 2, 0], [1, 3, 0], [1, 4, 0], [2, 2, 0], [2, 2, 1], [2, 3, 0], [2, 3, 1]]

Total number of states: 8
ETA: 0.94

Results:  E = -2.904778 ,  eta = 0.94000 
Reference optimized values from the book:   E_ref = -2.897109  ,  eta_ref = 0.94000  ,  dE = 0.0076690


In [26]:
cc5.overlap

array([[ 1.      , -0.707107,  0.      ,  0.      ,  0.5     ,  0.      ,  0.      ,  0.      ],
       [-0.707107,  1.25    , -0.612372,  0.      , -1.414214,  0.      ,  0.433013,  0.      ],
       [ 0.      , -0.612372,  1.5     , -0.866025,  0.866025,  0.      , -1.06066 ,  0.      ],
       [ 0.      ,  0.      , -0.866025,  2.      ,  0.      ,  0.      ,  0.612372,  0.      ],
       [ 0.5     , -1.414214,  0.866025,  0.      ,  4.      ,  0.      , -2.44949 ,  0.      ],
       [ 0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  4.      ,  0.      , -2.      ],
       [ 0.      ,  0.433013, -1.06066 ,  0.612372, -2.44949 ,  0.      ,  3.75    ,  0.      ],
       [ 0.      ,  0.      ,  0.      ,  0.      ,  0.      , -2.      ,  0.      ,  3.5     ]])

In [27]:
cc5.hamiltonian0

array([[-0.88    ,  0.66468 ,  0.      ,  0.      , -0.5     ,  0.      ,  0.      ,  0.      ],
       [ 0.66468 , -0.66    ,  0.57563 ,  0.      ,  0.66468 ,  0.      , -0.433013,  0.      ],
       [ 0.      ,  0.57563 , -0.38    ,  0.814064, -0.866025,  0.      ,  0.33234 ,  0.      ],
       [ 0.      ,  0.      ,  0.814064, -0.35    ,  0.      ,  0.      , -0.612372,  0.      ],
       [-0.5     ,  0.66468 , -0.866025,  0.      ,  0.24    ,  0.      ,  1.15126 ,  0.      ],
       [ 0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.24    ,  0.      ,  0.94    ],
       [ 0.      , -0.433013,  0.33234 , -0.612372,  1.15126 ,  0.      , -0.1     ,  0.      ],
       [ 0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.94    ,  0.      ,  0.15    ]])

In [28]:
cc5.hamiltonianW

array([[ 0.29375 , -0.103856, -0.050879, -0.022031,  0.088125, -0.118718,  0.017988, -0.029679],
       [-0.103856,  0.220312, -0.035977, -0.031157, -0.197327,  0.125919,  0.025439, -0.041973],
       [-0.050879, -0.035977,  0.198281, -0.034979,  0.089038,  0.007344, -0.116838,  0.075273],
       [-0.022031, -0.031157, -0.034979,  0.199199,  0.038555, -0.01802 ,  0.04722 ,  0.01537 ],
       [ 0.088125, -0.197327,  0.089038,  0.038555,  0.565469, -0.190796, -0.229353,  0.136737],
       [-0.118718,  0.125919,  0.007344, -0.01802 , -0.190796,  0.815156,  0.038946, -0.203789],
       [ 0.071954, -0.031799, -0.132417,  0.060711, -0.121422, -0.054525,  0.380039, -0.110347],
       [-0.029679, -0.041973,  0.075273,  0.01537 ,  0.136737, -0.203789, -0.133715,  0.509473]])

In [29]:
cc5.eigenvalues

array([-2.904778, -1.842498, -0.070346,  0.207621,  0.558194,  4.130179,  8.682971, 11.448476])

# n12 = 6

In [30]:
n = 6

cc6 = Configurations(n, Z=2, eta=0.796)
#E_opt, eta_opt = cc6.optimize_eta()
E = cc6.get_energy()

States: [[1, 1, 0], [1, 2, 0], [1, 3, 0], [1, 4, 0], [1, 5, 0], [2, 2, 0], [2, 2, 1], [2, 3, 0], [2, 3, 1], [2, 4, 0], [2, 4, 1], [3, 3, 0], [3, 3, 1], [3, 3, 2]]

Total number of states: 14
ETA: 0.796

Results:  E = -2.925969 ,  eta = 0.79600 
Reference optimized values from the book:   E_ref = -2.900714  ,  eta_ref = 0.79600  ,  dE = 0.0252545


In [31]:
cc6.overlap

array([[ 1.      , -0.707107,  0.      ,  0.      ,  0.      ,  0.5     ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [-0.707107,  1.25    , -0.612372,  0.      ,  0.      , -1.414214,  0.      ,  0.433013,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      , -0.612372,  1.5     , -0.866025,  0.      ,  0.866025,  0.      , -1.06066 ,  0.      ,  0.612372,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      , -0.866025,  2.      , -1.118034,  0.      ,  0.      ,  0.612372,  0.      , -1.414214,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      , -1.118034,  2.5     ,  0.      ,  0.      ,  0.      ,  0.      ,  0.790569,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.5     , -1.414214,  0.866025,  0.      ,  0.      ,  4.      ,  0.      , -2.44949 ,  0.      ,  0.      ,  0.      ,  1.5     ,  0.      ,  0.      ],
       [ 0.      ,  0.

In [32]:
cc6.hamiltonian0

array([[-0.592   ,  0.562857,  0.      ,  0.      ,  0.      , -0.5     ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.562857, -0.444   ,  0.487448,  0.      ,  0.      ,  0.562857,  0.      , -0.433013,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.487448, -0.092   ,  0.689356,  0.      , -0.866025,  0.      ,  0.281428,  0.      , -0.612372,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.689356,  0.01    ,  0.889955,  0.      ,  0.      , -0.612372,  0.      ,  0.281428,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      ,  0.889955,  0.112   ,  0.      ,  0.      ,  0.      ,  0.      , -0.790569,  0.      ,  0.      ,  0.      ,  0.      ],
       [-0.5     ,  0.562857, -0.866025,  0.      ,  0.      ,  0.816   ,  0.      ,  0.974897,  0.      ,  0.      ,  0.      , -1.5     ,  0.      ,  0.      ],
       [ 0.      ,  0.

In [33]:
cc6.hamiltonianW

array([[ 0.24875 , -0.087946, -0.043085, -0.018656, -0.006953,  0.074625, -0.100531,  0.015233, -0.025133, -0.004397,  0.003406,  0.018656, -0.030518,  0.037545],
       [-0.087946,  0.186562, -0.030466, -0.026384, -0.017207, -0.167098,  0.106629,  0.021542, -0.035543,  0.017102, -0.034121, -0.006596,  0.018406, -0.066371],
       [-0.043085, -0.030466,  0.167906, -0.029621, -0.024085,  0.075398,  0.006219, -0.09894 ,  0.063742,  0.030466, -0.015732, -0.021542, -0.018656,  0.024085],
       [-0.018656, -0.026384, -0.029621,  0.168684, -0.027811,  0.032648, -0.015259,  0.039986,  0.013015, -0.103887,  0.05237 , -0.009328,  0.021094,  0.015644],
       [-0.006953, -0.017207, -0.024085, -0.027811,  0.170627,  0.006953, -0.012043,  0.025546, -0.008028,  0.033185,  0.013646,  0.005215,  0.015555,  0.001166],
       [ 0.074625, -0.167098,  0.075398,  0.032648,  0.006953,  0.478844, -0.161568, -0.194218,  0.11579 , -0.074754,  0.04428 ,  0.130594, -0.120278,  0.146008],
       [-0.100531,  0.

In [34]:
cc6.eigenvalues

array([-2.925969, -1.88243 , -0.406426,  0.010056,  0.439591,  2.630346,  3.5209  ,  3.869601,  5.322626,  7.024769, 11.923541, 14.174112, 25.36117 , 30.391832])

# n12 = 7

In [35]:
n = 7

cc7 = Configurations(n, Z=2, eta=0.760)
#E_opt, eta_opt = cc.optimize_eta()
E = cc7.get_energy()

States: [[1, 1, 0], [1, 2, 0], [1, 3, 0], [1, 4, 0], [1, 5, 0], [1, 6, 0], [2, 2, 0], [2, 2, 1], [2, 3, 0], [2, 3, 1], [2, 4, 0], [2, 4, 1], [2, 5, 0], [2, 5, 1], [3, 3, 0], [3, 3, 1], [3, 3, 2], [3, 4, 0], [3, 4, 1], [3, 4, 2]]

Total number of states: 20
ETA: 0.76

Results:  E = -2.950597 ,  eta = 0.76000 
Reference optimized values from the book:   E_ref = -2.901452  ,  eta_ref = 0.76000  ,  dE = 0.0491450


In [36]:
cc7.overlap

array([[ 1.      , -0.707107,  0.      ,  0.      ,  0.      ,  0.      ,  0.5     ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ],
       [-0.707107,  1.25    , -0.612372,  0.      ,  0.      ,  0.      , -1.414214,  0.      ,  0.433013,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ],
       [ 0.      , -0.612372,  1.5     , -0.866025,  0.      ,  0.      ,  0.866025,  0.      , -1.06066 ,  0.      ,  0.612372,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      , -0.866025,  2.      , -1.118034,  0.      ,  0.      ,  0.      ,  0.612372,  0.      , -1.414214,  0.      ,  0.790569,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      , -1.118034, 

In [37]:
cc7.hamiltonian0

array([[-0.52    ,  0.537401,  0.      ,  0.      ,  0.      ,  0.      , -0.5     ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ],
       [ 0.537401, -0.39    ,  0.465403,  0.      ,  0.      ,  0.      ,  0.537401,  0.      , -0.433013,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.465403, -0.02    ,  0.658179,  0.      ,  0.      , -0.866025,  0.      ,  0.268701,  0.      , -0.612372,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.658179,  0.1     ,  0.849706,  0.      ,  0.      ,  0.      , -0.612372,  0.      ,  0.268701,  0.      , -0.790569,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      ,  0.849706, 

In [38]:
cc7.hamiltonianW

array([[ 0.2375  , -0.083969, -0.041136, -0.017813, -0.006638, -0.001818,  0.07125 , -0.095984,  0.014544, -0.023996, -0.004198,  0.003252, -0.007041,  0.008815,  0.017812, -0.029138,  0.035847,
         0.007713, -0.013821,  0.021952],
       [-0.083969,  0.178125, -0.029088, -0.025191, -0.016429, -0.008999, -0.159541,  0.101807,  0.020568, -0.033936,  0.016328, -0.032577,  0.004979, -0.013821, -0.006298,  0.017574, -0.063369,
         0.001818, -0.000958, -0.015522],
       [-0.041136, -0.029088,  0.160312, -0.028281, -0.022996, -0.016269,  0.071988,  0.005937, -0.094465,  0.060859,  0.029088, -0.015021,  0.018293, -0.02423 , -0.020568, -0.017813,  0.022996,
        -0.005195,  0.00399 , -0.026991],
       [-0.017813, -0.025191, -0.028281,  0.161055, -0.026553, -0.021816,  0.031172, -0.014569,  0.038178,  0.012427, -0.099188,  0.050001,  0.028164, -0.007665, -0.008906,  0.02014 ,  0.014936,
        -0.010284, -0.009756,  0.016261],
       [-0.006638, -0.016429, -0.022996, -0.026553, 

In [39]:
cc7.eigenvalues

array([-2.950597, -1.958684, -0.955645, -0.330962,  0.106209,  1.196784,  1.661094,  2.15452 ,  2.879548,  3.692492,  5.880168,  6.829286,  8.39178 ,  8.756003, 10.63143 , 15.107119, 20.267902,
       29.02881 , 42.60887 , 49.788317])